Feature/first pymc example
Posterior-ia/pymc_experiments pull request #5
Opened 2024-12-19 18:43 UTC by gabrielortegaproyectos

## Pull Request: Updates to Documentation and Dependencies

This pull request includes updates to the project documentation and dependency management. The most important change is the implementation of an example notebook with a functional PyMC example, specifically the linear regression tutorial. Additional updates include documentation improvements and dependency adjustments.

### Highlights of the PR

1. **Implementation of PyMC Example Notebook**:
   - Added a section to the `README.md` showcasing an example notebook that implements the official PyMC linear regression tutorial, making it easier for users to understand and utilize PyMC in their projects.

2. **Documentation Updates**:
   - [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R19): Included detailed instructions and references to the example notebook.

3. **Dependency Management Updates**:
   - [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L12-R20): Adjusted the `numpy` version requirement to `==1.26.0`.
   - [`pyproject.toml`](diffhunk://#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L12-R20): Added `bambi` and `watermark` as new dependencies to support the notebook examples and reproducibility.

2024-12-19 21:14 UTC, NicoCaro requested changes
Please rewrite the markdown cells for better readability and ease of editing.

2024-12-19 21:14 UTC, NicoCaro commented on notebooks/first_pymc_example.ipynb
These cells should be written in markdown, not html.

2024-12-24 22:30 UTC, gabrielortegaproyectos commented on notebooks/first_pymc_example.ipynb
All requested changes have been made. Please review the updates when you have a chance. Thank you!

2024-12-26 20:53 UTC, NicoCaro approved these changes

2024-12-26 20:53 UTC, merged